FROM amd64/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN apt-get update && apt-get install -y bash net-tools && apt-get clean

RUN useradd -ms /bin/bash Kron

RUN mkdir /etc/Kron

RUN mkdir /var/lib/Kron

RUN chown Kron:Kron /etc/Kron /var/lib/Kron

WORKDIR /home/Kron

COPY --chown=Kron:Kron linux64/* /home/Kron/

COPY --chown=Kron:Kron run.sh /home/Kron/

USER Kron

CMD ["/home/Kron/run.sh"]
